modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "adxero"
version = "${version}"
displayName = "Ad Astra Xero"
updateJSONURL = "https://api.modrinth.com/updates/gITClFhp/forge_updates.json"
authors = "Teddy0008 (Real owner), Dandi2k8 (Co-owner)"
description = "A mod to extend Ad Astra with new planets, rocket tiers, and more!"
logoFile = "logo.png"

[[dependencies.adxero]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adxero]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adxero]]
modId = "ad_astra"
mandatory = true
versionRange = "[1.15.19,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.adxero]]
modId = "botarium"
mandatory = true
versionRange = "[2.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adxero]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.23,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adxero]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "NONE"
side = "BOTH"